baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'boot documentation'
theme = 'hextra'

[params.navbar]
displayLogo = false
logo = {path = 'images/logo.jpg' }

[params.theme]
default = "system"
displayToggle = true

[params.search]
enable = true
type = 'flexsearch'
flexsearch = {index = "summary", tokenize = "forward"}

[[module.imports]]
path = 'github.com/imfing/hextra'
