[params.navbar]
logo = {path = 'images/logo.jpg'}

[[menus.main]]
name = 'Search'
weight = 5
params = {type = 'search'}

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Documentation'
pageRef = '/docs'
weight = 20

[[menus.main]]
name = "GitHub"
weight= 30
url= "https://github.com/bootengine/boot"
params = { icon = 'github'}

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
